# Generated by Django 3.1.2 on 2020-10-30 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 29, 11, 28, 27, 269141)),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_text',
            field=models.TextField(max_length=1500),
        ),
    ]
