# Generated by Django 3.1.2 on 2020-10-30 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201030_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 30, 11, 30, 47, 40383)),
        ),
    ]
