# Generated by Django 3.1.2 on 2020-10-30 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_blog_blog_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_date',
            field=models.CharField(default=12, max_length=20),
            preserve_default=False,
        ),
    ]
