# Generated by Django 3.1.2 on 2020-10-30 11:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_blog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 29, 11, 42, 1, 778524)),
        ),
    ]
