# Generated by Django 3.1.2 on 2020-11-03 11:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201030_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 3, 11, 2, 0, 278244)),
        ),
    ]
