# Generated by Django 3.1.2 on 2020-11-16 11:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20201116_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=50)),
                ('blog_date', models.DateTimeField(default=datetime.datetime(2020, 12, 16, 11, 36, 32, 193768))),
                ('blog_text', models.TextField(max_length=1500)),
                ('blog_image', models.ImageField(upload_to='blog_images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
