# Generated by Django 3.1.2 on 2020-11-16 11:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20201116_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 12, 16, 11, 38, 50, 868383))),
                ('text', models.TextField(max_length=1500)),
                ('image', models.ImageField(upload_to='blog_images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
